apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
metadata:
  name: thermometer-tcp
spec:
  adaptor:
    node: edge-worker
    name: adaptors.edge.cattle.io/modbus
    parameters:
      syncInterval: 5
      timout: 10
  model:
    apiVersion: "devices.edge.cattle.io/v1alpha1"
    kind: "ModbusDevice"
  template:
    metadata:
      labels:
        device: modbus-tcp
    spec:
      protocol:
        tcp:
          ip: 10.43.56.156
          port: 5020
          slaveID: 1
      properties:
      - name: temperature
        description: "temperature value, should be divided by 10"
        readOnly: true
        visitor:
          register: HoldingRegister
          offset: 0
          quantity: 1
          orderOfOperations:
          - operationType: Divide
            operationValue: "10"
        dataType: float
      - name: humidity
        description: "humidity value, should be divided by 10"
        readOnly: true
        visitor:
          register: HoldingRegister
          offset: 1
          quantity: 1
          orderOfOperations:
          - operationType: Divide
            operationValue: "10"
        dataType: float
      - name: alert
        description: the value reaches alert limitation
        readOnly: true
        visitor:
          register: CoilRegister
          offset: 0
          quantity: 1
        dataType: boolean
      - name: limitation
        description: the limitation
        readOnly: false
        value: "200"
        visitor:
          register: HoldingRegister
          offset: 5
          quantity: 1
          orderOfOperations:
          - operationType: Divide
            operationValue: "10"
        dataType: float
